### ISSUE TITLE
How to load extension

### ISSUE THREAD

**Issue by imv2d** [ejfasting/MonacoTest#1]
Hi, It seems you are able to load the extension vsix file in monaco editor that is working in browser.

I don't know much about monaco-vscode-api but would like to create a basic editor that will support the extension vsix file.
e.g. in my case I want RobotCode or RobotFramework Language Server extension which are available for vscode, to be used in my monaco editor and angular app.
so whenever I load my angular app on localhost:4200, monaco editor should load and extension should support.
It would be great if you can provide any details on this.
I don't want every features of the extension but at least code completion, formatting and basic features should work.

https://marketplace.visualstudio.com/items?itemName=d-biehl.robotcode

**Comment by ejfasting** [comment]
Hello @imv2d, 

This project was just a quick setup to import an existing .vsix into the monaco editor. It worked as expected, but I ended up going a different route for my scenario. 

I'm not sure you can just import that into a web editor (like monaco), as i see its not supported for [vscode.dev](https://code.visualstudio.com/docs/editor/vscode-web#_extensions). Most probably that extension does not launch the LSP server as a webworker, so i suspect you would have to create an extension meant to be used for the web, and import that .vsix into monaco.. 
That being said you could always give it a shot 👍 

It is actually [monaco-vscode-rollup-vsix-plugin](https://github.com/CodinGame/monaco-vscode-api#loading-vsix-file) that enables you do import a .vsix into monaco. It bridges the gap between the vscode API and the monaco API.
You could try to fork this repo and just replace the [import-statement](https://github.com/ejfasting/MonacoTest/blob/305e4ad0d0d8d74b5bc9fea11a692eaca0b5a9e6/src/main.ts#L2). 

Out of curiosity, how did you stumble upon this project/repo? 

//E
